#![cfg(test)]

use crate::{Groth16Proof, SettlementIntent, ZeroPathSettlement, ZeroPathSettlementClient};
use soroban_sdk::{
    testutils::Address as _,
    token::{StellarAssetClient, TokenClient},
    Address, BytesN, Env,
};

fn setup() -> (Env, ZeroPathSettlementClient<'static>, Address, Address) {
    let env = Env::default();
    env.mock_all_auths();
    let contract_id = env.register(ZeroPathSettlement, ());
    let client = ZeroPathSettlementClient::new(&env, &contract_id);
    let admin = Address::generate(&env);
    let relayer = Address::generate(&env);
    (env, client, admin, relayer)
}

#[test]
fn test_initialize() {
    let (_env, client, admin, relayer) = setup();
    client.initialize(&admin, &relayer);
}

#[test]
#[should_panic(expected = "already initialized")]
fn test_double_initialize() {
    let (_env, client, admin, relayer) = setup();
    client.initialize(&admin, &relayer);
    client.initialize(&admin, &relayer);
}

#[test]
fn test_update_source_root() {
    let (env, client, admin, relayer) = setup();
    client.initialize(&admin, &relayer);
    let root = BytesN::from_array(&env, &[1u8; 32]);
    client.update_source_root(&relayer, &root);
}

#[test]
#[should_panic(expected = "not relayer")]
fn test_update_source_root_wrong_relayer() {
    let (env, client, admin, relayer) = setup();
    client.initialize(&admin, &relayer);
    let impostor = Address::generate(&env);
    let root = BytesN::from_array(&env, &[1u8; 32]);
    client.update_source_root(&impostor, &root);
}

#[test]
fn test_pause_unpause() {
    let (_env, client, admin, relayer) = setup();
    client.initialize(&admin, &relayer);
    client.pause(&admin);
    client.unpause(&admin);
}

#[test]
#[should_panic(expected = "not admin")]
fn test_pause_wrong_admin() {
    let (env, client, admin, relayer) = setup();
    client.initialize(&admin, &relayer);
    let impostor = Address::generate(&env);
    client.pause(&impostor);
}

#[test]
fn test_negate_g1_generator() {
    let env = Env::default();

    // BN254 generator G1 = (1, 2) in big-endian 64-byte encoding
    let mut point_bytes = [0u8; 64];
    point_bytes[31] = 1; // x = 1
    point_bytes[63] = 2; // y = 2
    let point = BytesN::from_array(&env, &point_bytes);

    let neg = ZeroPathSettlement::negate_g1(&env, &point);
    let neg_bytes = neg.to_array();

    // x should be unchanged
    assert_eq!(neg_bytes[31], 1, "x coordinate should be preserved");
    for i in 0..31 {
        assert_eq!(neg_bytes[i], 0, "x high bytes should be zero");
    }

    // Negated y = p - 2
    // p = 0x30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd47
    // p - 2 = 0x30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd45
    // Last byte: 0x47 - 2 = 0x45
    assert_eq!(neg_bytes[63], 0x45, "last byte of negated y should be 0x45");
    // First byte of y should match first byte of p
    assert_eq!(neg_bytes[32], 0x30, "first byte of negated y should match p");
}

// ===========================================================================
// End-to-end Groth16 verification tests
//
// The proof and public-input vectors below are a REAL Groth16 BN254 proof for
// demo leaf 0, generated by circuits/gen-test-vector.mjs using the exact same
// Poseidon Merkle tree construction as the relayer. Before emission, the
// generator runs snarkjs.groth16.verify against build/verification_key.json —
// the same verification key hardcoded into lib.rs — so these vectors are a
// valid (proof, public inputs) pair for this contract's verifier.
//
// Regenerate with:  cd circuits && node gen-test-vector.mjs
// ===========================================================================

// ----- AUTO-GENERATED by circuits/gen-test-vector.mjs — do not edit by hand -----
const PROOF_A: [u8; 64] = [
    0x2f, 0xe4, 0xf1, 0x2c, 0x6c, 0x47, 0xc5, 0xf2, 0xde, 0xe3, 0x4d, 0xc8,
    0xd4, 0xa8, 0xd4, 0x55, 0x66, 0x19, 0xee, 0xae, 0x04, 0x78, 0x52, 0x73,
    0x50, 0xbd, 0xae, 0xb4, 0xc6, 0xda, 0x0b, 0xc5, 0x06, 0x56, 0xf8, 0xa2,
    0xab, 0xaa, 0x90, 0x65, 0x1f, 0x33, 0x01, 0x1a, 0x8e, 0x26, 0x89, 0xa8,
    0x1a, 0x5b, 0x76, 0xe9, 0xd1, 0x1a, 0x10, 0x5a, 0xba, 0xeb, 0xe9, 0x51,
    0x47, 0x13, 0xe3, 0x23,
];

const PROOF_B: [u8; 128] = [
    0x2c, 0x3c, 0x3d, 0x5b, 0x12, 0x3c, 0xd1, 0xa5, 0xea, 0x2c, 0xbe, 0x03,
    0xa5, 0x74, 0x72, 0x3f, 0x40, 0x98, 0x1c, 0x21, 0x1f, 0xb0, 0x08, 0x91,
    0x90, 0x6b, 0xa2, 0x69, 0x0a, 0x83, 0xf9, 0x63, 0x18, 0x80, 0xab, 0xce,
    0xd8, 0x10, 0x82, 0x6b, 0x32, 0x8b, 0x07, 0x4e, 0x76, 0x67, 0x04, 0x5c,
    0x69, 0x2e, 0xb4, 0x7e, 0xe9, 0x99, 0xe4, 0x78, 0x9c, 0x3a, 0xa8, 0xd1,
    0xb3, 0xad, 0x30, 0x61, 0x0a, 0x9a, 0x45, 0x29, 0x00, 0x0e, 0xc0, 0x88,
    0xde, 0x65, 0xc2, 0xa3, 0xa2, 0xff, 0x22, 0x03, 0x5d, 0xea, 0xbe, 0x48,
    0x33, 0x23, 0xdf, 0xce, 0x6b, 0x91, 0x6d, 0xc1, 0x1c, 0xf9, 0xc2, 0x5d,
    0x24, 0xeb, 0x95, 0x0c, 0xb0, 0xf8, 0xf6, 0xf8, 0x7d, 0x5b, 0xf3, 0x51,
    0xb3, 0x33, 0x0a, 0xfb, 0xff, 0x3c, 0x29, 0x2c, 0x0b, 0xcf, 0x3e, 0x37,
    0xcc, 0x41, 0x35, 0x4b, 0x7c, 0x31, 0xad, 0x40,
];

const PROOF_C: [u8; 64] = [
    0x20, 0xd4, 0xbe, 0xa3, 0xb6, 0x89, 0x9f, 0x9b, 0xd5, 0xdb, 0xc1, 0x99,
    0x58, 0x03, 0xd6, 0xb6, 0xa2, 0xe7, 0x87, 0xa3, 0xc1, 0x45, 0x5f, 0x7f,
    0x98, 0x2d, 0x3f, 0xd8, 0x51, 0x6c, 0x0a, 0x95, 0x2b, 0x1f, 0x45, 0xce,
    0x52, 0xbc, 0x20, 0xe6, 0xb6, 0x6a, 0x21, 0xc7, 0xce, 0xdb, 0x26, 0xdc,
    0x94, 0x75, 0xd4, 0xd6, 0x4c, 0x65, 0xeb, 0x5e, 0x30, 0x90, 0x40, 0x67,
    0x76, 0xb5, 0x67, 0xda,
];

const PI_BATCH_ROOT: [u8; 32] = [
    0x11, 0x00, 0x96, 0xb9, 0x63, 0xb0, 0x23, 0xa6, 0xfa, 0x9f, 0x48, 0xe8,
    0x5f, 0x4f, 0xde, 0xb1, 0x2a, 0xe1, 0xa6, 0x56, 0xc8, 0xb3, 0xf8, 0xf2,
    0x0c, 0xb2, 0x98, 0x8c, 0x9a, 0x28, 0x04, 0xfb,
];

const PI_SOURCE_EVENT_ROOT: [u8; 32] = [
    0x12, 0xbe, 0xa8, 0x16, 0x68, 0xe6, 0x99, 0x45, 0x67, 0xb7, 0x8c, 0x97,
    0xe1, 0xe3, 0x34, 0x1a, 0x83, 0xc5, 0x02, 0xd1, 0xfb, 0xde, 0x50, 0x7b,
    0xd8, 0x52, 0xc5, 0x29, 0x29, 0xfc, 0xbd, 0x28,
];

const PI_NULLIFIER_HASH: [u8; 32] = [
    0x28, 0xcd, 0x27, 0x1c, 0x08, 0x30, 0x71, 0xb8, 0x46, 0x6f, 0xcd, 0x5c,
    0x6d, 0x0c, 0xd9, 0x01, 0xf9, 0x54, 0x1d, 0xdc, 0x11, 0x78, 0x4c, 0xc5,
    0x09, 0xdc, 0x12, 0x58, 0x3d, 0x34, 0xc6, 0x21,
];

const PI_DESTINATION_COMMITMENT: [u8; 32] = [
    0x1b, 0xc5, 0x5f, 0xa8, 0x42, 0x35, 0xd7, 0x07, 0x27, 0x73, 0xd9, 0x34,
    0xb3, 0x22, 0x0e, 0x9e, 0xaa, 0xf3, 0xaf, 0xf3, 0x2f, 0x01, 0x35, 0x3f,
    0x71, 0x0a, 0xc7, 0x79, 0x79, 0x78, 0xc0, 0x81,
];

const PI_ASSET_ID: [u8; 32] = [
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
];

// epoch public input as u64 = 4219
const PI_EPOCH: u64 = 4219;
// ----- END AUTO-GENERATED -----

const SETTLE_AMOUNT: i128 = 5_000;

/// Full environment for a settle() call: initialized contract, a funded
/// Stellar Asset token, a recipient, and the relayer-submitted source root.
struct SettleFixture {
    env: Env,
    client: ZeroPathSettlementClient<'static>,
    contract_id: Address,
    recipient: Address,
    token: Address,
}

fn settle_fixture() -> SettleFixture {
    let env = Env::default();
    env.mock_all_auths();

    let contract_id = env.register(ZeroPathSettlement, ());
    let client = ZeroPathSettlementClient::new(&env, &contract_id);

    let admin = Address::generate(&env);
    let relayer = Address::generate(&env);
    let recipient = Address::generate(&env);
    client.initialize(&admin, &relayer);

    // Deploy a Stellar Asset Contract token and fund the settlement contract
    // so it can pay out the recipient on a successful settle().
    let token_admin = Address::generate(&env);
    let sac = env.register_stellar_asset_contract_v2(token_admin);
    let token = sac.address();
    StellarAssetClient::new(&env, &token).mint(&contract_id, &SETTLE_AMOUNT);

    // Relayer publishes the source-event root the proof commits to.
    let source_root = BytesN::from_array(&env, &PI_SOURCE_EVENT_ROOT);
    client.update_source_root(&relayer, &source_root);

    SettleFixture { env, client, contract_id, recipient, token }
}

fn valid_proof(env: &Env) -> Groth16Proof {
    Groth16Proof {
        a: BytesN::from_array(env, &PROOF_A),
        b: BytesN::from_array(env, &PROOF_B),
        c: BytesN::from_array(env, &PROOF_C),
    }
}

fn valid_intent(env: &Env, recipient: &Address, token: &Address) -> SettlementIntent {
    SettlementIntent {
        batch_root: BytesN::from_array(env, &PI_BATCH_ROOT),
        source_event_root: BytesN::from_array(env, &PI_SOURCE_EVENT_ROOT),
        nullifier_hash: BytesN::from_array(env, &PI_NULLIFIER_HASH),
        destination_commitment: BytesN::from_array(env, &PI_DESTINATION_COMMITMENT),
        asset_id: BytesN::from_array(env, &PI_ASSET_ID),
        epoch: PI_EPOCH,
        recipient: recipient.clone(),
        token: token.clone(),
        amount_bucket: SETTLE_AMOUNT,
    }
}

/// The core claim: a real Groth16 proof is verified on-chain by the CAP-0074
/// pairing check, and only then are funds released to the recipient.
#[test]
fn test_settle_accepts_real_proof_and_pays_recipient() {
    let f = settle_fixture();
    let intent = valid_intent(&f.env, &f.recipient, &f.token);
    let proof = valid_proof(&f.env);

    f.client.settle(&intent, &proof);

    let token_client = TokenClient::new(&f.env, &f.token);
    assert_eq!(token_client.balance(&f.recipient), SETTLE_AMOUNT, "recipient funded");
    assert_eq!(token_client.balance(&f.contract_id), 0, "contract drained");
}

/// Replay protection: the nullifier is consumed, so the same proof cannot
/// settle twice.
#[test]
#[should_panic(expected = "nullifier spent")]
fn test_settle_rejects_replay() {
    let f = settle_fixture();
    let intent = valid_intent(&f.env, &f.recipient, &f.token);
    let proof = valid_proof(&f.env);

    // Fund a second payout so the failure can only be the nullifier check.
    StellarAssetClient::new(&f.env, &f.token).mint(&f.contract_id, &SETTLE_AMOUNT);

    f.client.settle(&intent, &proof);
    f.client.settle(&intent, &proof); // panics: nullifier spent
}

/// A tampered proof must fail the pairing check. We swap pi_a and pi_c: both
/// are valid on-curve G1 points (so the host's point parsing succeeds), but
/// they no longer satisfy the Groth16 pairing equation, so verify_groth16
/// returns false and the contract panics with "invalid proof".
#[test]
#[should_panic(expected = "invalid proof")]
fn test_settle_rejects_tampered_proof() {
    let f = settle_fixture();
    let intent = valid_intent(&f.env, &f.recipient, &f.token);

    let proof = Groth16Proof {
        a: BytesN::from_array(&f.env, &PROOF_C), // swapped
        b: BytesN::from_array(&f.env, &PROOF_B),
        c: BytesN::from_array(&f.env, &PROOF_A), // swapped
    };

    f.client.settle(&intent, &proof); // panics: invalid proof
}

/// A structurally malformed proof (a point that is not on the BN254 curve) is
/// rejected by the CAP-0074 host functions before the pairing check completes.
/// The transaction still aborts, so no funds move.
#[test]
#[should_panic(expected = "Error(Crypto, InvalidInput)")]
fn test_settle_rejects_malformed_proof_point() {
    let f = settle_fixture();
    let intent = valid_intent(&f.env, &f.recipient, &f.token);

    let mut bad_c = PROOF_C;
    bad_c[63] ^= 0x01; // flip a bit so pi_c is no longer on the curve
    let proof = Groth16Proof {
        a: BytesN::from_array(&f.env, &PROOF_A),
        b: BytesN::from_array(&f.env, &PROOF_B),
        c: BytesN::from_array(&f.env, &bad_c),
    };

    f.client.settle(&intent, &proof); // panics: Error(Crypto, InvalidInput)
}

/// Tampering a public input (asset_id) changes vk_x, so the otherwise-valid
/// proof no longer satisfies the pairing equation.
#[test]
#[should_panic(expected = "invalid proof")]
fn test_settle_rejects_tampered_public_input() {
    let f = settle_fixture();
    let mut intent = valid_intent(&f.env, &f.recipient, &f.token);

    let mut bad_asset = PI_ASSET_ID;
    bad_asset[31] = 0x02; // claim asset_id = 2 instead of the proven 1
    intent.asset_id = BytesN::from_array(&f.env, &bad_asset);

    f.client.settle(&intent, &valid_proof(&f.env)); // panics: invalid proof
}

/// settle() must refuse a source-event root the relayer never published, even
/// with an otherwise valid proof.
#[test]
#[should_panic(expected = "unverified source root")]
fn test_settle_rejects_unpublished_root() {
    let env = Env::default();
    env.mock_all_auths();
    let contract_id = env.register(ZeroPathSettlement, ());
    let client = ZeroPathSettlementClient::new(&env, &contract_id);
    let admin = Address::generate(&env);
    let relayer = Address::generate(&env);
    let recipient = Address::generate(&env);
    client.initialize(&admin, &relayer);

    let token_admin = Address::generate(&env);
    let token = env.register_stellar_asset_contract_v2(token_admin).address();
    StellarAssetClient::new(&env, &token).mint(&contract_id, &SETTLE_AMOUNT);

    // Note: no update_source_root() call here.
    let intent = valid_intent(&env, &recipient, &token);
    client.settle(&intent, &valid_proof(&env)); // panics: unverified source root
}
